#服务器端口
server:
  port: 8106

#数据源配置
spring:
  datasource:
#    url: ${blade.datasource.dev.url}
#    username: ${blade.datasource.dev.username}
#    password: ${blade.datasource.dev.password}

#文件的物理路径前缀与url前缀
fileserver:
  path-prefix: ${fileserver.dev.path}
  url-prefix: ${fileserver.dev.url}
  photoLogo: ${fileserver.dev.photoLogo}
  key: ${fileserver.dev.key}
#  key: abcdefgabcdefg12
alarmserver:
  address-path: ${alarmserver.dev.address}
