#服务器端口
server:
  port: 9104

#数据源配置
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    #    url: ${blade.datasource.dev.url}
    #    username: ${blade.datasource.dev.username}
    #    password: ${blade.datasource.dev.password}


    #测试
    url: jdbc:mysql://rm-2vcu2m013irzt8gm5bo.mysql.cn-chengdu.rds.aliyuncs.com:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: anbiao
    password: Ts2022*

#文件的物理路径前缀与url前缀
fileserver:
#  path-prefix: ${fileserver.dev.path}
#  url-prefix: ${fileserver.dev.url}

    path-prefix: 'D:\BS\static\'
    url-prefix: 'http://127.0.0.1:8204/'
