#服务器端口
server:
  port: 9102

#数据源配置
spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    url: ${blade.datasource.dev.url}
    username: ${blade.datasource.dev.username}
    password: ${blade.datasource.dev.password}

    #测试
    #        url: jdbc:mysql://120.78.198.161:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    #        username: root
    #        password: Ts2022

    #    url: jdbc:mysql://221.10.137.57:22438/blade?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true
    #    username: root
    #    password: admin@xs

    #    url: jdbc:mysql://202.105.11.193:3366/blade_qg?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    #    username: root
    #    password: admin@gzqy

    driver-class-name: com.mysql.jdbc.Driver    #指定数据库驱动
    type: com.alibaba.druid.pool.DruidDataSource  #指定类型连接池
    #数据源其他配置
    initialSize: 5  #初始化连接数
    minIdle: 5      #最小空闲连接数getDeptById
    maxActive: 20   #最大连接数
    maxWait: 60000  #最大等待值
    timeBetweenEvictionRunsMillis: 60000  #// 连接回收器的运行周期时间，时间到了清理池中空闲的连接，testWhileIdle根据这个判断
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL  #//用来检测连接是否有效的sql，要求是一个查询语句
    testWhileIdle: true   #//建议配置为true，不影响性能，并且保证安全性。 申请连接的时候检测，如果空闲时间大于
    testOnBorrow: false     #//申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。设置为false
    testOnReturn: false  # //归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能,设置为flase
    poolPreparedStatements: true  # //是否缓存preparedStatement，也就是PSCache
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20  # // 池中能够缓冲的preparedStatements语句数量
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

#文件的物理路径前缀与url前缀
fileserver:
  path-prefix: ${fileserver.dev.path}
  url-prefix: ${fileserver.dev.url}
  gpsVehiclePath: ${fileserver.dev.gpsVehiclePath}
  #  离线时间阀值
  maxOfflineTime: 900
  learnRecordUrl: http://r.bn.cloudjoytech.com.cn/sec/getLearnRecord
  markRemindScore: 750
  video-url: ${fileserver.dev.videoUrl}

alarmserver:
  templateUrl: D:\BS\static\SafetyStandards\
  address-ak: ${fileserver.dev.ak}

trainserver:
  search-score: 60
